language: cpp

install:
    - cd ${TRAVIS_BUILD_DIR}

before_script:
    - cd ${TRAVIS_BUILD_DIR}
    - git submodule update --init
    - mkdir build && cd build
    - cmake ..
compiler:
    - clang
    - gcc
script:
    - cd ${TRAVIS_BUILD_DIR}
    - make
    - make test
    - cd ..
after_success:
    - cd ${TRAVIS_BUILD_DIR}
