language: cpp

install:
    - cd ${TRAVIS_BUILD_DIR}

before_script:
    - cd ${TRAVIS_BUILD_DIR}

      # Compiler selection
compiler:
    - clang
    - gcc


      # Build steps
script:
    - git submodule update --init
    - cd ${TRAVIS_BUILD_DIR}
    - cmake ..
    - make
    - make test

after_success:
    - cd ${TRAVIS_BUILD_DIR}
