language: cpp

install:
    - echo "install..."
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
    - travis_retry wget --no-check-certificate https://cmake.org/files/v3.20/cmake-3.20.0-linux-x86_64.tar.gz
    - tar -xvf cmake-3.20.0-linux-x86_64.tar.gz > /dev/null
    - mv cmake-3.20.0-linux-x86_64 cmake-install
    - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
    - cd ${TRAVIS_BUILD_DIR}
before_script:
    - echo "before script..."
    - cd ${TRAVIS_BUILD_DIR}
    - mkdir build
    - cd build
    - cmake ../
compiler:
    - clang
    - gcc
script:
    - cd ${TRAVIS_BUILD_DIR}
    - echo "script..."
    - pwd
    - make
    - make test
after_success:
    - cd ${TRAVIS_BUILD_DIR}
